jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: azure-gradle.yml
    parameters:
      wrapper: gradlew
      tasks: test distZip
  - task: CopyFiles@2
    inputs:
      sourceFolder: build/distributions/
      contents: '*.zip'
      targetFolder: $(Build.ArtifactStagingDirectory)/dist
      cleanTargetFolder: true
      overWrite: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
      artifactName: 'dist'
      publishLocation: 'Container'

- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - template: azure-gradle.yml
    wrapper: gradlew.bat
