version: "3"

services:
  # Run without db service with "docker-compose up --no-deps party"
  party:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: openalcoholics/cocktailparty
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cocktail
