/**
* API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package group.openalcoholics.cocktailparty.models


/**
 * A cocktail category.
 * @param id The category ID
 * @param name The name of the category
 * @param description The description for the category
 * @param imageLink A link to an image representing the category
 */
data class CocktailCategory (
    /* The category ID */
    val id: kotlin.Int,
    /* The name of the category */
    val name: kotlin.String,
    /* The description for the category */
    val description: kotlin.String,
    /* A link to an image representing the category */
    val imageLink: kotlin.String? = null
): BaseModel<CocktailCategory> {
    override fun withId(id: Int): CocktailCategory {
        return copy(id = id)
    }
}

