/**
* API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package group.openalcoholics.cocktailparty.models


/**
 * Information about the implementation serving the API.
 * @param name The name of the server implementation.
 * @param version The version of the implementation
 * @param projectInfo URL to the project website
 */
data class ImplementationInfo (
    /* The name of the server implementation. */
    val name: kotlin.String,
    /* The version of the implementation */
    val version: kotlin.String,
    /* URL to the project website */
    val projectInfo: kotlin.String? = null
) {

}

