/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package group.openalcoholics.cocktailparty.models

/**
 * Information about the implementation serving the API.
 * @param name The name of the server implementation.
 * @param version The version of the implementation
 * @param projectInfo URL to the project website
 */
data class ImplementationInfo(
    val name: kotlin.String,
    val version: kotlin.String,
    val projectInfo: kotlin.String? = null
)

