/**
* API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.1.0
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package group.openalcoholics.cocktailparty.models

import com.fasterxml.jackson.annotation.JsonProperty
import org.jdbi.v3.core.mapper.reflect.ColumnName


/**
 * An ingredient category.
 * @param id The category ID
 * @param name The name of the category
 * @param alcoholic Whether ingredients of this category contain alcohol
 * @param imageLink A link to an image representing the category
 */
data class IngredientCategory (
    /* The category ID */
    val id: kotlin.Int,
    /* The name of the category */
    val name: kotlin.String,
    /* A description of the category */
    val description: String,
    /* Whether ingredients of this category contain alcohol */
    @ColumnName("is_alcoholic")
    val alcoholic: kotlin.Boolean,
    /* A link to an image representing the category */
    val imageLink: kotlin.String? = null
): BaseModel<IngredientCategory> {
    override fun withId(id: Int): IngredientCategory {
        return copy(id = id)
    }
}

