/**
* API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package group.openalcoholics.cocktailparty.models

import group.openalcoholics.cocktailparty.models.ImplementationInfo

/**
 * Describes the server version.
 * @param apiVersion The API version
 * @param implementation 
 */
data class Version (
    /* The API version */
    val apiVersion: kotlin.String,
    val implementation: ImplementationInfo
) {

}

