# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:8-jdk

    - image: circleci/postgres:10.5
      environment:
        POSTGRES_DB: cocktail_test
        POSTGRES_USER: testuser
        POSTGRES_PASSWORD: testpass # fuck it, I can't use env vars here

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init
    - run: chmod +x gradlew

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle.kts" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: ./gradlew dependencies
    - run: ./gradlew flywayMigrate

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle.kts" }}

    # run tests!
    - run: ./gradlew test

    - store_test_results:
        path: build/test-results
