version: 2
jobs:
  test:
    docker:
    - image: circleci/openjdk:8-jdk
    - image: circleci/postgres:10.5-alpine
      environment:
        POSTGRES_DB: cocktail_test
        POSTGRES_USER: testuser
        POSTGRES_PASSWORD: testpass # fuck it, I can't use env vars here

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init
    - run: chmod +x gradlew

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle.kts" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: ./gradlew dependencies
    - run: ./gradlew flywayMigrate

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle.kts" }}

    # run tests!
    - run: ./gradlew test

    - store_test_results:
        path: build/test-results

  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t openalcoholics/cocktailparty:latest-$CIRCLE_BRANCH .

      # deploy the image
      - run: docker push openalcoholics/cocktailparty:latest-$CIRCLE_BRANCH

  deploy:
    docker:
      - image: byrnedo/alpine-curl:latest
    # Update server image
    steps:
      - run: curl -L "http://ec2-52-59-248-193.eu-central-1.compute.amazonaws.com:8080?key=$UPDATE_KEY"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              # Disabled until CD-ready
              # only:
              #   - master
              #   - develop
              ignore: /.*/
