version: 2.1
executors:
  openjdk:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false


commands:
  recursive_checkout:
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init


jobs:
  compile:
    executor: openjdk
    steps:
      - recursive_checkout
      - run: chmod +x gradlew

        # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
              # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      - run: ./gradlew classes

      - persist_to_workspace:
          root: .
          paths:
            - build
            - buildSrc/build


  test:
    executor: openjdk
    # We also want postgres for this one
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/postgres:10.5-alpine
        environment:
          POSTGRES_DB: cocktail_test
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass # fuck it, I can't use env vars here
    steps:
      - recursive_checkout
      - run: chmod +x gradlew

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - attach_workspace:
          at: .

      - run: ./gradlew flywayMigrate
      - run: ./gradlew test

      - store_test_results:
          path: build/test-results


  build:
    executor: openjdk
    steps:
      - recursive_checkout
      - run: chmod +x gradlew

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - attach_workspace:
          at: .

      - run: ./gradlew assembleDist -x check -x test
      - store_artifacts:
          path: build/distributions/
          destination: distribution


  build_docker:
    docker:
      - image: docker:18.06-git
    working_directory: ~/repo
    parameters:
      docker_tag:
        description: "The docker tag name"
        type: string
    steps:
      - recursive_checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - attach_workspace:
          at: .

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t openalcoholics/cocktailparty:<<parameters.docker_tag>> .

      # deploy the image
      - run: docker push openalcoholics/cocktailparty:<<parameters.docker_tag>>


  deploy:
    docker:
      - image: byrnedo/alpine-curl:latest
    # Update server image
    steps:
      - run: curl -L "http://ec2-52-59-248-193.eu-central-1.compute.amazonaws.com:8080?key=$UPDATE_KEY"


  markdown_lint:
    docker:
      - image: 06kellyjac/markdownlint-cli:0.13.0-alpine
    steps:
      - checkout
      - run: markdownlint README.md


workflows:
  version: 2
  do_everything:
    jobs:
      - markdown_lint
      - compile
      - test:
          requires:
            - compile
      - build:
          requires:
            - compile
      - build_docker:
          name: BuildDockerBranch
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
          docker_tag: latest-$CIRCLE_BRANCH
      - build_docker:
          name: BuildDockerTag
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
          docker_tag: $CIRCLE_TAG
